author: Matteo Tagliatti
url: "https://matteotagliatti.it"
email: matteotagliatti@gmail.com

social-network-links:
  github: https://github.com/matteotagliatti
  instagram: https://www.instagram.com/matteotagliatti/
  linkedin: https://www.linkedin.com/in/matteotagliatti/
  libri: /libri.html

collections:
  lavori:
    output: true
    order:
      - centrufficiooutlet.md
      - studio-acqua-tortona.md
      - centrosposiparadiso.md
      - template-html.md
      - futsalvigevano.md
      - motostore.md
      - aep.md

defaults:
  - scope:
      path: ""
      type: "lavori"
    values:
      layout: "lavori"

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude these files from production site
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md